project:
  type: website
  output-dir: _site
  resources:
    - assets/teaching/**
  render:
    - index.qmd
    - research.qmd
    - code.qmd
    - teaching.qmd
    - conferences.qmd
    - news.qmd
    - posts/**.qmd
    - cv.qmd

website:
  title: "Riccardo Di Francesco"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: code.qmd
        text: Code
      - href: teaching.qmd
        text: Teaching
      - href: conferences.qmd
        text: Conferences
      - href: news.qmd
        text: News
      - href: cv.qmd
        text: CV

format:
  html:
    theme: defualt
    toc: false
    smooth-scroll: true
    css: styles.css
