---
title: "Conferences"
toc: false
page-layout: full
---

## 2025

::: {.keywords}
<span class="keyword">*Annual Conference of the International Association for Applied Econometrics* (IAAE)</span>
<span class="keyword">*16th International Health Economics Association World Congress* (IHEA)</span>
<span class="keyword">*38th Annual Conference of the European Society for Population Economics* (ESPE)</span>
<span class="keyword">*11th Italian Congress of Econometrics and Empirical Economics* (ICEEE)</span>
:::

## 2024

::: {.keywords}
<span class="keyword">*CSQIEP Virtual Seminar*</span>
<span class="keyword">*Rome Conference on Econometrics: Frontiers in Casual Inference*</span>
<span class="keyword">*3rd Rome Ph.D. in Economics and Finance Conference*</span>
<span class="keyword">*29th International Panel Data Conference* (IPDC)</span>
<span class="keyword">*Annual Conference of the International Association for Applied Econometrics* (IAAE Thessaloniki)</span>
<span class="keyword">*Annual Conference of the International Association for Applied Econometrics* (IAAE Xiamen)</span>
<span class="keyword">*Annual Conference of the Scottish Economic Society* (SES)</span>
:::

## 2023

::: {.keywords}
<span class="keyword">*2nd Rome Ph.D. in Economics and Finance Conference*</span>
<span class="keyword">*11th SIdE Workshop for Ph.D. students in Econometrics and Empirical Economics* (WEEE)</span>
<span class="keyword">*10th Italian Congress of Econometrics and Empirical Economics* (ICEEE)</span>
:::

## 2022

::: {.keywords}
<span class="keyword">*1st Rome Ph.D. in Economics and Finance Conference*</span>
<span class="keyword">*10th SIdE Workshop for Ph.D. students in Econometrics and Empirical Economics* (WEEE)</span>
:::
