---
title: "Teaching"
toc: false
page-layout: full
---

## Academic year 2025/2026

::: {.callout-note appearance="minimal"}
### **Guest Lecturer$—$Microeconometrics**

::: {.small}
*Master of Science course*  
*Taught by Giovanni Mellace*  
*University of Southern Denmark, Odense*
:::

I delivered two guest lectures integrating theory, implementation, and applied case studies.

<div class="paper-actions teaching-actions">
  <span class="teaching-label">📊 Slides:</span>
  <a class="btn btn-paper" href="https://riccardo-df.github.io/assets/teaching/2025-26/Microeconometrics/DiscreteOutcomes.html">Discrete outcomes</a>
  <a class="btn btn-paper" href="https://riccardo-df.github.io/assets/teaching/2025-26/Microeconometrics/causalML.html">Causal machine learning</a>
</div>

<div class="paper-actions teaching-actions">
  <span class="teaching-label">💻 Notebooks:</span>
  <a class="btn btn-code" href="https://riccardo-df.github.io/assets/teaching/2025-26/Microeconometrics/LeagueofLogits.html">League of Logits</a>
  <a class="btn btn-code" href="https://riccardo-df.github.io/assets/teaching/2025-26/Microeconometrics/GoodBadOrdinal.html">Ordinal outcomes</a>
</div>
:::

## Academic year 2023/2024

::: {.callout-note appearance="minimal"}
### **Teaching Assistant$—$Statistics**

::: {.small}
*Bachelor of Science course*  
*Taught by Livia De Giovanni*  
*LUISS University, Rome*
:::

I assisted students in implementing R code for the analysis of real data sets. Students completed an empirical project and submitted a written report, which I evaluated and graded.
:::

::: {.callout-note appearance="minimal"}
### **Teaching Assistant$—$Applied Statistics and Econometrics**

::: {.small}
*Bachelor of Science course*  
*Taught by Marianna Brunetti*  
*LUISS University, Rome*
:::

Students completed a research project as part of the course requirements. I supported them in formulating research questions, collecting data, applying econometric methods, and I assessed the final projects.
:::

## Academic year 2021/2022

::: {.callout-note appearance="minimal"}
### **Teaching Assistant$—$Statistical Learning**

::: {.small}
*Master of Science course*  
*Taught by Tommaso Proietti*  
*University of Rome Tor Vergata, Rome*
:::

I conducted interactive tutorials focused on the practical application of machine learning methods in R, with an emphasis on hands-on data analysis and interpretation.
:::
